# Generated by Django 4.0.5 on 2022-07-03 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docter_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_specimen', models.CharField(max_length=50)),
                ('specimen_size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=6, null=True)),
                ('number_of_slides', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('pathology_number', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('report_issued_at', models.DateField(default=2022)),
                ('groos_examination', models.TextField(blank=True)),
                ('microscopic_examination', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('signature', models.CharField(blank=True, max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_has_a_report', to='search.patient')),
                ('specimen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimen_belongs_to_report', to='Report_app.specimen')),
                ('user', models.ManyToManyField(blank=True, through='Report_app.Docter_Report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='docter_report',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Report_app.report'),
        ),
    ]
