# Generated by Django 4.0.5 on 2022-07-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('patient_name', models.CharField(default='patient_name', max_length=50)),
                ('patient_Nid', models.CharField(default='12348615', max_length=14)),
                ('patient_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('patient_age', models.PositiveIntegerField(default='21')),
                ('referring_physician_name', models.CharField(max_length=60)),
                ('referring_physician_deprt', models.CharField(max_length=60)),
                ('referring_physician_phone', models.BigIntegerField()),
                ('Clinical_History_And_Investigation', models.TextField()),
                ('Previous_pathology_report', models.TextField()),
                ('Nature_of_the_specimen', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('report_created', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_has_a_request', to='search.patient')),
            ],
        ),
    ]
