# Generated by Django 4.0.5 on 2022-07-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default=False, max_length=50)),
                ('patient_age', models.IntegerField(default=False)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('patient_type', models.CharField(choices=[('OS', 'OS'), ('S', 'S'), ('R', 'R'), ('M', 'M')], default='OS', max_length=10)),
                ('patient_phone', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('patient_NID', models.CharField(default='1234568', max_length=20)),
            ],
        ),
    ]
